export { default as GamesHubView } from './ui/GamesHubView.vue'
export { default as PriceBattleView } from './ui/PriceBattleView.vue'
export { default as FlowGameView } from './ui/FlowGameView.vue'
export { default as MemoryGameView } from './ui/MemoryGameView.vue'
export { default as CommunityGameHubView } from './ui/CommunityGameHubView.vue'
export { default as BasketGameView } from './ui/BasketGameView.vue'
